### ISSUE TITLE
老哥 能改oc版本吗

### ISSUE THREAD

**Issue by zhangruiyu** [CarnegieTechnologies/gallery_saver#14]
我这边跑不起来
![image](https://user-images.githubusercontent.com/10591822/63086646-ecbd6680-bf82-11e9-9870-dd91eff30757.png)

**Comment by ailic88** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by MrLiuYS** [comment]
```
  gallery_saver:
    git:
      url: https://github.com/MrLiuYS/gallery_saver.git
      ref: oc
```
