### ISSUE TITLE
PLEASE UPDATE DEPENDENCIES

### ISSUE THREAD

**Issue by carrasc0** [CarnegieTechnologies/gallery_saver#209]
Specially http

**Comment by mafreud** [comment]
I updated all dependencies. Use this.
https://github.com/ARTISAN-inc/gallery_saver_updated

**Comment by JonasJW** [comment]
@mafreud how do I use this?

When I do
````
  gallery_saver: 
    git:
      url: https://github.com/ARTISAN-inc/gallery_saver_updated.git
      ref: master
````
I get this error:
````
Resolving dependencies...
Error on line 1, column 7: "name" field doesn't match expected name "gallery_saver".
  ╷
1 │ name: gallery_saver_updated
  │       ^^^^^^^^^^^^^^^^^^^^^
  ╵
exit code 65
````
