### ISSUE TITLE
Gallery_Saver_Swift.h not found

### ISSUE THREAD

**Issue by ffahadMalikk** [CarnegieTechnologies/gallery_saver#42]
I tried to add this package for the purpose of saving network image into my gallery for both iOS and android but the moment i run my application its giving me this error providing in this line . 
Version i am using :   gallery_saver: ^1.0.7

**Comment by zhpoo** [comment]
I found the resolution. 
Insert the code lines in example into your ios/Podfile file.

`  use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
`

**Comment by MrLiuYS** [comment]
gallery_saver:
    git:
      url: https://github.com/MrLiuYS/gallery_saver.git
      ref: oc

**Comment by MrLiuYS** [comment]
```
  gallery_saver:
    git:
      url: https://github.com/MrLiuYS/gallery_saver.git
      ref: oc
```
